// THIS FILE IS AUTOGENERATED BY THE MAKEFILE. DO NOT EDIT.

package version

import (
	"fmt"
	"strconv"
)

var (
	version        string
	buildDate      string
	commitHash     string
	author         = "Alain Lefebvre <hartfordfive@gmail.com>"
	symbolsEnabled string
)

// PrintVersion returns the current version information
func PrintVersion() {
	fmt.Printf("Version %s, Date: %s, Commit: %s\nAuthor: %s\n", version, buildDate, commitHash, author)
	if b, _ := strconv.ParseBool(symbolsEnabled); b {
		fmt.Printf("Debug symbols enabled: %v\n", b)
	}
}
